import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { UsersProvider } from "@/context/ContextData";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UsersProvider>
            {children}
        </UsersProvider>
      </body>
    </html>
  );
}
